import Providers from "@/lib/Providers";
import "./globals.css";
import type { Metadata } from "next";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata: Metadata = {
  title: "Shoe House",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          {children}
          <ToastContainer />
        </body>
      </html>
    </Providers>
  );
}
